### ISSUE TITLE
Bug: Failure occurred during job recovery: Failed to obtain DB connection from data source 'default'

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1189]
## Expected Behavior

Portal should start correctly if the connection string is well defined.

## Current Behavior

WebSite startup failed.

## Steps to Reproduce

N/A

## Context (Environment)

**Portal version**:  v3.0-dev
**LoRaWAN Stack version**: N/A

## Logs

```
2022-09-09T17:33:37.891552066Z [41m[30mfail[39m[22m[49m: Quartz.Impl.AdoJobStore.JobStoreTX[0]
2022-09-09T17:33:37.892214086Z       Failure occurred during job recovery: Failed to obtain DB connection from data source 'default': System.ArgumentException: Couldn't set defaultendpointsprotocol (Parameter 'defaultendpointsprotocol')
2022-09-09T17:33:37.892232287Z        ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
2022-09-09T17:33:37.892238587Z          at Npgsql.NpgsqlConnectionStringBuilder.GeneratedSetter(String keyword, Object value)
2022-09-09T17:33:37.892243287Z          at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
2022-09-09T17:33:37.892247887Z          --- End of inner exception stack trace ---
2022-09-09T17:33:37.892252287Z          at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
2022-09-09T17:33:37.892256888Z          at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
2022-09-09T17:33:37.892261188Z          at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
2022-09-09T17:33:37.892265488Z          at Npgsql.NpgsqlConnection.GetPoolAndSettings()
2022-09-09T17:33:37.892269788Z          at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
2022-09-09T17:33:37.894131244Z          at Quartz.Impl.AdoJobStore.Common.DbProvider.CreateConnection()
2022-09-09T17:33:37.894180646Z          at Quartz.Util.DBConnectionManager.GetConnection(String dataSourceName)
2022-09-09T17:33:37.894192346Z          at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()
2022-09-09T17:33:37.894196946Z       Quartz.JobPersistenceException: Failed to obtain DB connection from data source 'default': System.ArgumentException: Couldn't set defaultendpointsprotocol (Parameter 'defaultendpointsprotocol')
2022-09-09T17:33:37.894201646Z        ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
2022-09-09T17:33:37.894220547Z          at Npgsql.NpgsqlConnectionStringBuilder.GeneratedSetter(String keyword, Object value)
2022-09-09T17:33:37.894224947Z          at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
2022-09-09T17:33:37.894228847Z          --- End of inner exception stack trace ---
2022-09-09T17:33:37.894232747Z          at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
2022-09-09T17:33:37.894236647Z          at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
2022-09-09T17:33:37.894240647Z          at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
2022-09-09T17:33:37.894244448Z          at Npgsql.NpgsqlConnection.GetPoolAndSettings()
2022-09-09T17:33:37.894248348Z          at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
2022-09-09T17:33:37.894252148Z          at Quartz.Impl.AdoJobStore.Common.DbProvider.CreateConnection()
2022-09-09T17:33:37.894256148Z          at Quartz.Util.DBConnectionManager.GetConnection(String dataSourceName)
2022-09-09T17:33:37.894260048Z          at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()
2022-09-09T17:33:37.894263848Z        ---> System.ArgumentException: Couldn't set defaultendpointsprotocol (Parameter 'defaultendpointsprotocol')
2022-09-09T17:33:37.894267948Z        ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
2022-09-09T17:33:37.894271948Z          at Npgsql.NpgsqlConnectionStringBuilder.GeneratedSetter(String keyword, Object value)
2022-09-09T17:33:37.894275849Z          at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
2022-09-09T17:33:37.894279749Z          --- End of inner exception stack trace ---
2022-09-09T17:33:37.894283549Z          at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
2022-09-09T17:33:37.894287549Z          at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
2022-09-09T17:33:37.894292749Z          at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
2022-09-09T17:33:37.894296849Z          at Npgsql.NpgsqlConnection.GetPoolAndSettings()
2022-09-09T17:33:37.894300749Z          at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
2022-09-09T17:33:37.894304549Z          at Quartz.Impl.AdoJobStore.Common.DbProvider.CreateConnection()
2022-09-09T17:33:37.894308850Z          at Quartz.Util.DBConnectionManager.GetConnection(String dataSourceName)
2022-09-09T17:33:37.894313250Z          at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()
2022-09-09T17:33:37.894317150Z          --- End of inner exception stack trace ---
2022-09-09T17:33:37.894320950Z          at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()
2022-09-09T17:33:37.894324850Z          at Quartz.Impl.AdoJobStore.JobStoreTX.GetNonManagedTXConnection()
2022-09-09T17:33:37.894333150Z          at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator, Nullable`1 requestorId, CancellationToken cancellationToken)
2022-09-09T17:33:37.894337450Z          at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator, Nullable`1 requestorId, CancellationToken cancellationToken)
2022-09-09T17:33:37.894341751Z          at Quartz.Impl.AdoJobStore.JobStoreSupport.SchedulerStarted(CancellationToken cancellationToken) [See nested exception: System.ArgumentException: Couldn't set defaultendpointsprotocol (Parameter 'defaultendpointsprotocol')
2022-09-09T17:33:37.894345851Z        ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
2022-09-09T17:33:37.894349951Z          at Npgsql.NpgsqlConnectionStringBuilder.GeneratedSetter(String keyword, Object value)
2022-09-09T17:33:37.894353851Z          at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
2022-09-09T17:33:37.894357851Z          --- End of inner exception stack trace ---
2022-09-09T17:33:37.894361651Z          at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
2022-09-09T17:33:37.894365451Z          at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
2022-09-09T17:33:37.894369351Z          at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
2022-09-09T17:33:37.894373251Z          at Npgsql.NpgsqlConnection.GetPoolAndSettings()
2022-09-09T17:33:37.894377052Z          at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
2022-09-09T17:33:37.894380852Z          at Quartz.Impl.AdoJobStore.Common.DbProvider.CreateConnection()
2022-09-09T17:33:37.894385152Z          at Quartz.Util.DBConnectionManager.GetConnection(String dataSourceName)
2022-09-09T17:33:37.894389052Z          at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()]
2022-09-09T17:33:38.185597058Z Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
2022-09-09T17:33:38.185638659Z    at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
2022-09-09T17:33:38.185645359Z    at Microsoft.EntityFrameworkCore.NpgsqlDbContextOptionsBuilderExtensions.UseNpgsql(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 npgsqlOptionsAction)
2022-09-09T17:33:38.185650259Z    at AzureIoTHub.Portal.Server.Startup.<>c__DisplayClass7_0.<ConfigureServices>b__3(DbContextOptionsBuilder opts) in /src/AzureIoTHub.Portal/Server/Startup.cs:line 105
2022-09-09T17:33:38.185655459Z    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass3_0`2.<AddDbContextPool>b__0(IServiceProvider _, DbContextOptionsBuilder ob)
2022-09-09T17:33:38.185660159Z    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass6_0`1.<AddPoolingOptions>b__0(IServiceProvider sp, DbContextOptionsBuilder ob)
2022-09-09T17:33:38.185664660Z    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
2022-09-09T17:33:38.185681760Z    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
2022-09-09T17:33:38.185686460Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2022-09-09T17:33:38.185690560Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2022-09-09T17:33:38.185694561Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2022-09-09T17:33:38.185698661Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2022-09-09T17:33:38.185702761Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2022-09-09T17:33:38.185707861Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2022-09-09T17:33:38.185712261Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2022-09-09T17:33:38.185716361Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2022-09-09T17:33:38.185720361Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2022-09-09T17:33:38.185724461Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2022-09-09T17:33:38.185728662Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
2022-09-09T17:33:38.185734162Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2022-09-09T17:33:38.185738162Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2022-09-09T17:33:38.185742162Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
2022-09-09T17:33:38.185746462Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2022-09-09T17:33:38.185750562Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2022-09-09T17:33:38.185757762Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2022-09-09T17:33:38.185762063Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2022-09-09T17:33:38.185766463Z    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__5`2.<AddDbContextPool>b__5_0(IServiceProvider sp)
2022-09-09T17:33:38.185770763Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2022-09-09T17:33:38.185774763Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2022-09-09T17:33:38.185778963Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
2022-09-09T17:33:38.185783063Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2022-09-09T17:33:38.185787163Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2022-09-09T17:33:38.185791163Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
2022-09-09T17:33:38.185795464Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2022-09-09T17:33:38.185799564Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2022-09-09T17:33:38.185803664Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2022-09-09T17:33:38.185807764Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2022-09-09T17:33:38.185811864Z    at AzureIoTHub.Portal.Server.Startup.EnsureDatabaseCreatedAndUpToDate(IApplicationBuilder app, IWebHostEnvironment env) in /src/AzureIoTHub.Portal/Server/Startup.cs:line 436
2022-09-09T17:33:38.185815964Z    at AzureIoTHub.Portal.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in /src/AzureIoTHub.Portal/Server/Startup.cs:line 408
2022-09-09T17:33:38.185820064Z    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2022-09-09T17:33:38.185824464Z    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
2022-09-09T17:33:38.185828565Z    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2022-09-09T17:33:38.185832465Z    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2022-09-09T17:33:38.193918209Z    at System.Threading.Thread.StartCallback()
2022-09-09T17:33:45.573Z ERROR - Container cgigeiotdemoportal_0_c36e977a for site cgigeiotdemoportal is not running, failing site start
```

**Comment by kbeaugrand** [comment]
Found the issue : 

The connectionString should be set in WebApp as Custom Type: 

![image](https://user-images.githubusercontent.com/9513635/189412690-f1f4560c-b7dd-4941-bf08-93703ec0b052.png)
