### ISSUE TITLE
Bug: Application loading issue with chrome

### ISSUE THREAD

**Issue by Sben65** [CGI-FR/IoT-Hub-Portal#1631]
## Current Behavior

When we try to access the portal from the chrome browser, we receive an error.

## Steps to Reproduce

1.
2.

## Context (Environment)

**Portal version**: v4.1.0
**LoRaWAN Stack version**: 

## Logs

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: ''
Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessTokenNotAvailableException: ''
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler.SendAsync(HttpRequestMessage , CancellationToken )
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__29`1[[System.Collections.Generic.List`1[[AzureIoTHub.Portal.Models.v10.IoTEdgeModelListItem, AzureIoTHub.Portal.Shared, Version=4.2.0.883, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at AzureIoTHub.Portal.Client.Services.EdgeModelClientService.GetIoTEdgeModelList()
   at AzureIoTHub.Portal.Client.Pages.EdgeDevices.EdgeDeviceListPage.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

**Comment by kbeaugrand** [comment]
@Sben65 or @hocinehacherouf , could you try to clear the cache-storage from your browser: 

<img width="629" alt="image" src="https://user-images.githubusercontent.com/9513635/205712490-1626dab5-6e46-4fab-8f36-d83d01507b1f.png">

Tell me after if the problem still appears.

**Comment by hocinehacherouf** [comment]
@kbeaugrand same issue after cache-storage

**Comment by kbeaugrand** [comment]
@hocinehacherouf I confirm that I'm also facing this issue on my CGI computer. 

Chrome version are the same between my personal computer and CGI. It seems that some policies are coming with this configuration that are blocking the storage of the oidc.user in the browser session storage. 

At this moment I don't have any information about what has been blocked... Still investigating.
