### ISSUE TITLE
Bug: MigrateDeviceModelCommands throws an exception

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#1988]
## Expected Behavior
We are migrating from v2.8.0 to the current latest release v4.8.0, the data from the Storage Account's tables should be migrated to the database.

## Current Behavior
During the PgSql initialization, there is an error during the migration of commands

## Steps to Reproduce
- Instantiate a Portal in version 2.8.0
- Add models and commands
- Update the image to 4.8.1
- Observe the world as it collapses

## Context (Environment)

**Portal version**: 4.8.1 (migrating from 2.8.0)
**LoRaWAN Stack version**: N/A

## Logs
```
[...] PgSql tables init [...]
2023-04-04T12:17:28.165472599Z Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
2023-04-04T12:17:28.165512100Z    at AzureIoTHub.Portal.Infrastructure.Seeds.DeviceModelCommandSeeder.MigrateDeviceModelCommands(PortalDbContext ctx, ConfigHandler config) in /src/AzureIoTHub.Portal.Infrastructure/Seeds/DeviceModelCommandSeeder.cs:line 28
2023-04-04T12:17:28.165518600Z    at AzureIoTHub.Portal.Server.Startup.EnsureDatabaseCreatedAndUpToDate(IApplicationBuilder app) in /src/AzureIoTHub.Portal.Server/Startup.cs:line 471
2023-04-04T12:17:28.165522100Z    at AzureIoTHub.Portal.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in /src/AzureIoTHub.Portal.Server/Startup.cs:line 433
2023-04-04T12:17:28.165525400Z    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2023-04-04T12:17:28.165529500Z    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2023-04-04T12:17:28.165532500Z    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

## Additional Information
Our Storage Account table doesn't have any `Name` column, which may explain the NullReferenceException. All other columns exist and there is no null value.

![image](https://user-images.githubusercontent.com/5247527/229794111-92a5f84a-2868-4713-bf47-75db16da7dbc.png)

**Comment by kbeaugrand** [comment]
@Metal-Mighty new release has been created: v4.8.2. could you try it ?

**Comment by Metal-Mighty** [comment]
DB creation ok with v4.8.2, thank you !
