### ISSUE TITLE
Bug: Failed to load some pages

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#2131]
## Expected Behavior

All the pages should load correctly.

## Current Behavior

After deploying to AWS staging, we are facing to some HTT 500 errors.

## Steps to Reproduce

1. Go to edge devices page
2. Go to edge model page

## Context (Environment)

**Portal version**: v5.x
**LoRaWAN Stack version**: N/A

## Logs

```json
{"type":"https://httpstatuses.io/500","title":"Internal Server Error","status":500,"traceId":"00-f581d08736cbd6a4ea9df565bd6f74cf-e3c12d2d164ebd76-00"}
```
```txt
05-31-2023 11:13:18 AM fail: Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware[1]
05-31-2023 11:13:18 AM          at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)
05-31-2023 11:13:18 AM          at NetEscapades.AspNetCore.SecurityHeaders.SecurityHeadersMiddleware.Invoke(HttpContext context) in /_/src/NetEscapades.AspNetCore.SecurityHeaders/SecurityHeadersMiddleware.cs:line 69
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
05-31-2023 11:13:18 AM       --- End of stack trace from previous location ---
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
05-31-2023 11:13:18 AM       --- End of stack trace from previous location ---
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
05-31-2023 11:13:18 AM          at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
05-31-2023 11:13:18 AM          at lambda_method223(Closure, IServiceProvider, Object[])
05-31-2023 11:13:18 AM          at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
05-31-2023 11:13:18 AM       System.InvalidOperationException: Unable to resolve service for type 'AzureIoTHub.Portal.Application.Services.IEdgeModelService' while attempting to activate 'AzureIoTHub.Portal.Server.Controllers.v10.EdgeModelsController'.
05-31-2023 11:13:18 AM       An unhandled exception has occurred while executing the request.
```

**Comment by kbeaugrand** [comment]
Well, ti CI was the issue. I fixed it by deploying an image tag containing the sha of the latest commit on the branch and deploying this image tag to the AppRunner during the CI.
