### ISSUE TITLE
Bug: Unhandled error when accessing the list of gateways

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#218]
## Expected Behavior

Display the list of configured gateways

## Current Behavior

No device displayed, the loading circle is present and an error strip is present at the bottom of the page

## Steps to Reproduce

1. Open Gateways > Overview

### Browser

Mozilla Firefox 91.1.0esr

### Container Operating System

Linux containers

#### Docker

N/A

## Logs

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
    Unhandled exception rendering component: net_http_message_not_success_statuscode, 500, Internal Server Error
System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode, 500, Internal Server Error
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__13`1[[System.Collections.Generic.List`1[[AzureIoTHub.Portal.Shared.Models.GatewayListItem, AzureIoTHub.Portal.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at AzureIoTHub.Portal.Client.Pages.Gateways.GatewayListPage.LoadGatewaysList()
   at AzureIoTHub.Portal.Client.Pages.Gateways.GatewayListPage.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )```

## Additional Information
<!-- Please provide any additional information that may be helpful in understanding the issue. -->
Using version 1.0.0

**Comment by kbeaugrand** [comment]
Regarding with @Metal-Mighty there are some changes to do on deployment template: 

- https://github.com/michelin/i4i-deployment/issues/86
- https://github.com/michelin/i4i-deployment/issues/88
