### ISSUE TITLE
Bug: Random failure on unit test DeviceConfigurationDetailPageShouldRenderProperties

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#684]
## Logs
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed DeviceConfigurationDetailPageShouldRenderProperties [27 ms]
  Error Message:
   System.InvalidOperationException : Sequence contains no matching element
  Stack Trace:
     at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at AzureIoTHub.Portal.Client.Pages.DeviceConfigurations.DeviceConfigurationDetailPage.<>c__DisplayClass0_3.<BuildRenderTree>b__69(RenderTreeBuilder __builder11) in /home/runner/work/IoT-Hub-Portal/IoT-Hub-Portal/src/AzureIoTHub.Portal/Client/Pages/DeviceConfigurations/DeviceConfigurationDetailPage.razor:line [16](https://github.com/CGI-FR/IoT-Hub-Portal/runs/6356260367?check_suite_focus=true#step:9:16)1
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudItem.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Bunit.Rendering.TestRenderer.AssertNoUnhandledExceptions() in /_/src/bunit.core/Rendering/TestRenderer.cs:line 384
   at Bunit.Rendering.TestRenderer.Render[TResult](RenderFragment renderFragment, Func`2 activator) in /_/src/bunit.core/Rendering/TestRenderer.cs:line 266
   at Bunit.Rendering.TestRenderer.RenderFragment(RenderFragment renderFragment) in /_/src/bunit.core/Rendering/TestRenderer.cs:line 49
   at Bunit.Extensions.TestContextBaseRenderExtensions.RenderInsideRenderTree(TestContextBase testContext, RenderFragment renderFragment) in /_/src/bunit.core/Extensions/TestContextBaseRenderExtensions.cs:line 43
   at Bunit.Extensions.TestContextBaseRenderExtensions.RenderInsideRenderTree[TComponent](TestContextBase testContext, RenderFragment renderFragment) in /_/src/bunit.core/Extensions/TestContextBaseRenderExtensions.cs:line 23
   at Bunit.TestContext.Render[TComponent](RenderFragment renderFragment) in /_/src/bunit.web/TestContext.cs:line 66
   at Bunit.TestContext.RenderComponent[TComponent](ComponentParameter[] parameters) in /_/src/bunit.web/TestContext.cs:line 36
   at AzureIoTHub.Portal.Server.Tests.Unit.Pages.DeviceConfigurationDetailPageTests.RenderComponent[TComponent](ComponentParameter[] parameters) in /home/runner/work/IoT-Hub-Portal/IoT-Hub-Portal/src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DeviceConfigurations/DeviceConfigurationDetailPageTests.cs:line 58
   at AzureIoTHub.Portal.Server.Tests.Unit.Pages.DeviceConfigurationDetailPageTests.DeviceConfigurationDetailPageShouldRenderProperties() in /home/runner/work/IoT-Hub-Portal/IoT-Hub-Portal/src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DeviceConfigurations/DeviceConfigurationDetailPageTests.cs:line 4[20](https://github.com/CGI-FR/IoT-Hub-Portal/runs/6356260367?check_suite_focus=true#step:9:20)
```

**Comment by hocinehacherouf** [comment]
Unable to reprodure the issue on the unit test DeviceConfigurationDetailPageShouldRenderProperties
